127 Add entry field for Associated Datasets
cioos-siooc/metadata-entry-form pull request #281
Opened 2023-11-23 05:52 UTC by fostermh

https://github.com/cioos-siooc/metadata-entry-form/issues/127

2023-11-24 21:25 UTC, fostermh commented
All changes other then merging the tabs have been completed

see https://github.com/cioos-siooc/metadata-entry-form/issues/127 for a discussion on why we may or may not want to merge resources and related tabs.

2023-11-30 17:34 UTC, Br-Johnson requested changes
- Related identifier field is required to be a full URL, but ISNN for example is not a URL. Remove requirement for it to be a full URL?
- Change 'Related' tab to 'Related Works'
- Word smith 'Resource' tab docs to identify that 'Resources' are the primary 'resource' that the metadata record describes.
- Word smith 'Related Works' documentation to make it clear this is for works published elsewhere

2023-12-02 05:15 UTC, fostermh commented
I think I have captured all the changes requested

2023-12-07 06:07 UTC, fostermh commented
ok, @timvdstap I think I have addressed your comments.

- translation fixed, the function was deployed without necessary aws credentials, my bad
- example of using 'Dependency' added
- yes, supporting documents such as sampling protocols would still go under resources. other cited works such as a published paper, a service built using data from this record, or an aggregated dataset of which this is a part would go under related works.
- validation now works. I did not know about the submit page or had forgotten, thanks for checking that.

2023-12-07 23:02 UTC, Br-Johnson requested changes
Some rewording to consistently use 'primary resource' to identify the resource the current metadata record being created is referring to, and to use related work to identify the 'associated dataset/resource' people are linking to. Also I tried to replace 'records' with either one of the previously mentioned terms.

Tried clarifying the language for relation Type to make it as clear as possible.

I also realized maybe you could include resource type (ie [MD_ScopeCode](https://wiki.esipfed.org/ISO_19115-3_Codelists#MD_ScopeCode)) for the primary resource. Maybe thats another issue though if it's not simple to implement.

2023-12-19 21:57 UTC, fostermh commented
I'm not sure that mapping 'crossReference' directly to cited is a good idea. In my mind crossReference is also for datasets that are siblings and part of the same collection but not necessarily citing each other. 

I found this [crosswalk](https://drive.google.com/open?id=1P6WH8h4OnIVR9UJj3FcOebNUpLnKNBCuvEp3NsLRho4) which has some suggestions on this site https://www.rd-alliance.org/groups/research-metadata-schemas-wg if you search for 'associationType' a few different things come up.

One mapping shows 'isReferencedBy' mapping to associated resources but suggests using the datacite list of relation types. One option would be to add a specific type to our list for example 'Cites' to populate datacite metadata with. When generating the iso19115 xml we would have to map 'Cites' back to something like crossReference. This is the only way I can see to capture all the info you are asking for while still staying true to the ISO standard.

2023-12-19 23:42 UTC, fostermh commented
I also wonder if mdb:MD_Metadata/mdb:resourceLineage/mrl:LI_Lineage/mrl:source/mrl:LI_Source/mrl:sourceCitation/cit:CI_Citation would be a better place to put things that are cited by this resource and thus contributed to its creation (lineage)
https://wiki.esipfed.org/LI_Source

2024-01-17 20:02 UTC, fostermh commented
TODO: change relationship type to use the datacite types and map these back to the iso standard.

2024-01-17 20:10 UTC, Br-Johnson commented
> TODO: change relationship type to use the datacite types and map these back to the iso standard.

Here's a google sheet where we can map the terms: https://docs.google.com/spreadsheets/d/1zanRa84k5TqdPbTekpwjPHnwGQoT6XpPKgBBlhGyS6s/edit?usp=sharing

2024-01-17 22:21 UTC, fostermh commented
this does not appear to be the full list of datacite relations types however? I thought the point was to list all the datacite options and then map them to iso

2024-01-17 22:23 UTC, Br-Johnson commented
Yeah exactly that's right. I was trying to update it before lunch but didn't get a chance

2024-01-22 20:24 UTC, Br-Johnson commented
Those updated DataCite to ISO mappings look great @fostermh

2024-01-24 17:42 UTC, fostermh commented
I think this is ready to go now. I have updated the relationship type to use the datacite list of values and mapped them to the iso list for iso XML output. The datacite relatedIdentifier field is now populated on datacite son output.

2024-01-25 22:25 UTC, Br-Johnson commented
OK cool. I'll have a look!

2024-02-08 23:09 UTC, Br-Johnson requested changes

2024-02-08 23:09 UTC, Br-Johnson commented on src/components/FormComponents/RelatedWorks.jsx
> +                  optionTooltips={Object.values(associationTypeCode).map(
I feel like the current Tooltip that describe how the DataCite relation types map to ISO isn't particularly useful for the user. Could you update the tooltip so it explains the DataCite relation type using the definitions here?: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/relationType/#issourceof

2024-02-08 23:09 UTC, Br-Johnson commented on src/components/Tabs/RelatedWorksTab.jsx
> +                  <li>Cross Reference - Reference from one record to another.	Use to identify related documents or related records that may be part of the same collection or project</li>
I actually think the description of how works can be related should be removed from the top header, and just explained using the Relation Type examples.

2024-03-07 01:20 UTC, fostermh commented
replaced by https://github.com/cioos-siooc/metadata-entry-form/pull/322

2024-03-07 01:20 UTC, closed without merging