Multiple Authors Access
cioos-siooc/metadata-entry-form pull request #324
Opened 2024-02-27 22:12 UTC by sorochak

2024-03-26 13:33 UTC, JessyBarrette commented
That's a nice add-on @sorochak. I'm wondering if it would be better to use suggestions based on what the user is typing instead a providing a dropdown of our whole list of user emails.

Maybe, it would also be better to use names (name/lastname) instead as a list/suggestion.

I'm more worried about peoples email privacy than anything.

2024-04-11 03:32 UTC, fostermh requested changes

2024-04-11 03:32 UTC, fostermh commented on firebase-functions/functions/datacite.js
> +exports.recordToDataCite = functions.https.onCall(async (data) => {
the datacite prefix isn't sensitive informaton so recordToDataCite dosn't need to be a firebase function. In order to keep it consistent with the other templates I Think it's better for this to be in the front end with the other templates files as it was.

2024-04-11 03:32 UTC, fostermh commented on firebase-functions/functions/datacite.js
> +    prefix = (await admin.database().ref('admin').child(region).child("dataciteCredentials").child("prefix").once("value")).val();
why not use getCredentialsStored here so you don't have to update db paths in multiple places?

2024-04-16 22:34 UTC, sorochak commented
Thank you for he input @JessyBarrette! It's now a searchable list of names.

2024-04-17 17:06 UTC, fostermh approved these changes

2024-04-17 21:13 UTC, merged